export const CITIZENSHIPS_TYPES = {
  LOAD_CITIZENSHIPS: 'CITIZENSHIPS_TYPES.LOAD_CITIZENSHIP',
  CREATE_CITIZENSHIP: 'CITIZENSHIPS_TYPES.CREATE_CITIZENSHIP',
  EDIT_CITIZENSHIP: 'CITIZENSHIPS_TYPES.EDIT_CITIZENSHIP',
  DELETE_CITIZENSHIP: 'CITIZENSHIPS_TYPES.DELETE_CITIZENSHIP',
}