export const COMMANDS_TYPES = {
  LOAD_COMMANDS: 'COMMANDS_TYPES.LOAD_COMMANDS',
  CREATE_COMMAND: 'COMMANDS_TYPES.CREATE_COMMAND',
  EDIT_COMMAND: 'COMMANDS_TYPES.EDIT_COMMAND',
  DELETE_COMMAND: 'COMMANDS_TYPES.DELETE_COMMAND',
}