export const PROFESSIONS_TYPES = {
  LOAD_PROFESSIONS: 'PROFESSIONS_TYPES.LOAD_PROFESSIONS',
  CREATE_PROFESSION: 'PROFESSIONS_TYPES.CREATE_PROFESSION',
  EDIT_PROFESSION: 'PROFESSIONS_TYPES.EDIT_PROFESSION',
  DELETE_PROFESSION: 'PROFESSIONS_TYPES.DELETE_PROFESSION',
}