export const STATUSES_TYPES = {
  LOAD_STATUSES: 'STATUSES_TYPES.LOAD_STATUSES',
  CREATE_STATUS: 'STATUSES_TYPES.CREATE_STATUS',
  EDIT_STATUS: 'STATUSES_TYPES.EDIT_STATUS',
  DELETE_STATUS: 'STATUSES_TYPES.DELETE_STATUS',
}